### ISSUE TITLE
Traceback in mgmtsystem_nonconformity

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/management-system#160]
Hello,

I get an error while installing the module mgmtsystem_nonconformity:

ValueError: External ID not found in the system: mgmtsystem_nonconformity.stage_draft

Thank in advance for any help.
Cas

**Comment by max3903** [comment]
Hello Cas,

Thank you for reporting the issue. Can you please mention the Odoo version you are using?

**Comment by CasVissers-360ERP** [comment]
Hi Max,

The modules are used on Odoo 9.0.

**Comment by max3903** [comment]
@CasVissers I just got the latest version of the module and was able to install it with demo data. Can you make sure you are using the latest version?

**Comment by CasVissers-360ERP** [comment]
Hi Max, I have a new traceback on a clean database:

2016-10-14 06:12:12,204 7580 INFO ? werkzeug: 127.0.0.1 - - [14/Oct/2016 06:12:12] "POST /web/database/create HTTP/1.1" 500 -
2016-10-14 06:12:12,220 7580 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "werkzeug\serving.py", line 177, in run_wsgi

  File "werkzeug\serving.py", line 165, in execute

  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\service\server.py", line 246, in app
    return self.app(e, s)
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\service\wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\service\wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\http.py", line 1494, in **call**
    self.load_addons()
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\http.py", line 1515, in load_addons
    m = **import**('openerp.addons.' + module)
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\modules\module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\custom\mgmtsystem_nonconformity__init__.py", line 21, in <module>
    from . import models, reports
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\custom\mgmtsystem_nonconformity\models__init__.py", line 6, in <module>
    from . import (
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\custom\mgmtsystem_nonconformity\models\mgmtsystem_nonconformity.py", line 9, in <module>
    class MgmtsystemNonconformity(models.Model):
  File "C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\custom\mgmtsystem_nonconformity\models\mgmtsystem_nonconformity.py", line 100, in MgmtsystemNonconformity
    default=_default_stage)
NameError: name '_default_stage' is not defined

**Comment by max3903** [comment]
@CasVissers Can you check at line 17 of C:\Program Files (x86)\Odoo 9.0-20160802\server\openerp\custom\mgmtsystem_nonconformity\models\mgmtsystem_nonconformity.py ?

That's where _default_stage is defined:
https://github.com/OCA/management-system/blob/9.0/mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py#L17
