### ISSUE TITLE
cannot install nonconformity on 13: Unknow field res.users.manager_user_id

### ISSUE THREAD

**Issue by drajar** [OCA/management-system#277]
2019-12-08 09:05:18,721 92124 INFO odoo odoo.modules.loading: loading mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
2019-12-08 09:05:18,957 92124 INFO odoo odoo.addons.base.models.ir_ui_view: Unknow field "res.users.manager_user_id" in domain of <field name="user_id"> "['|','|',('user_id','=',uid),('responsible_user_id','=',uid),('manager_user_id','=',uid)]"

View name: mgmtsystem.nonconformity.filter
Error context:
 view: ir.ui.view(3438,)
 xmlid: view_mgmtsystem_nonconformity_filter
 view.model: mgmtsystem.nonconformity
 file: /mnt/data/opt/odoo/addons/mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml

2019-12-08 09:05:18,975 92124 WARNING odoo odoo.modules.loading: Transient module states were reset
2019-12-08 09:05:18,989 92124 ERROR odoo odoo.modules.registry: Failed to load registry
2019-12-08 09:05:18,990 92124 ERROR odoo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 353, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 922, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 523, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 394, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 381, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 468, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 578, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 727, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 794, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 675, in _tag_root
    etree.tostring(rec, encoding='unicode').rstrip()
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 632, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /mnt/data/opt/odoo/addons/mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml:28, near
```
<record id="view_mgmtsystem_nonconformity_filter" model="ir.ui.view">
    <field name="name">mgmtsystem.nonconformity.filter</field>
    <field name="model">mgmtsystem.nonconformity</field>
    <field name="arch" type="xml">
      <search>
        <group name="filters">
          <filter name="draft" icon="terp-document-new" domain="[('state','=','draft')]" string="Draft" help="Draft/New nonconformities"/>
          <filter name="pending" icon="terp-gtk-media-pause" domain="[('state','in',['analysis','pending'])]" string="Analysis" help="Nonconformities pending review"/>
          <filter name="current" icon="terp-check" domain="[('state','=','open')]" string="In Progress" help="Open Nonconformities"/>
          <filter name="icon" icon="terp-camera_test" domain="[('state','=','done')]" string="Closed" help="Closed Nonconformities"/>
          <separator orientation="vertical"/>
          <field name="ref"/>
          <field name="create_date"/>
          <field name="user_id" string="User" domain="['|','|',('user_id','=',uid),('responsible_user_id','=',uid),('manager_user_id','=',uid)]"/>
          <field name="system_id"/>
          <field name="company_id" groups="base.group_multi_company"/>
        </group>
        <newline/>
        <group expand="0" string="Group By...">
          <filter name="groupby_author" string="Author" icon="gtk-edit" context="{'group_by':'user_id'}"/>
          <filter name="groupby_responsible" string="Responsible" icon="terp-personal" context="{'group_by':'responsible_user_id'}"/>
          <filter name="groupby_manager" string="Manager" icon="terp-personal+" context="{'group_by':'manager_user_id'}"/>
          <separator orientation="vertical"/>
          <filter name="groupby_system" string="System" icon="gtk-execute" context="{'group_by':'system_id'}"/>
          <filter name="groupby_partner" string="Partner" icon="terp-personal+" domain="[]" context="{'group_by':'partner_id'}"/>
          <filter name="groupby_procedure" string="Procedure" icon="terp-stock_symbol-selection" context="{'group_by':'procedure_ids'}"/>
        </group>
        </search>
      </field>
    </record>

```

**Comment by pedrobaeza** [comment]
You haven't installed the module properly (maybe you are using the import module option, which is not valid). Any way, this is working, so closing.

**Comment by drajar** [comment]
I installed management-system from sources. I cannot install nonconformity neither from settings checking nonconformity settings, neither from apps. The same error occurs.

**Comment by pedrobaeza** [comment]
You can check in https://runbot.odoo-community.org/runbot/128/13.0 that the module gets installed without problems.
