### ISSUE TITLE
cannot create action in 13.0

### ISSUE THREAD

**Issue by drajar** [OCA/management-system#278]
```
2019-12-08 12:02:51,925 107395 DEBUG odoo odoo.api: call mgmtsystem.action().create({'stage_id': 1, 'priority': '0', 'name': 'Optimizare proces vanzare', 'user_id': 2, 'sequence': 10, 'company_id': 1, 'type_action': 'prevention', 'date_deadline': '2019-12-15', 'tag_ids': [[6, False, []]], 'description': '<p><br></p>', 'system_id': False, 'message_attachment_count': 0})
2019-12-08 12:02:51,944 107395 DEBUG odoo odoo.addons.base.models.ir_sequence: No ir.sequence has been found for code 'mgmtsystem.action'. Please make sure a sequence is set for current company.
2019-12-08 12:02:51,990 107395 ERROR odoo odoo.sql_db: bad query: INSERT INTO "mgmtsystem_action" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "company_id", "date_deadline", "description", "name", "priority", "reference", "sequence", "stage_id", "system_id", "type_action", "user_id") VALUES (nextval('mgmtsystem_action_id_seq'), 2, (now() at time zone 'UTC'), 2, (now() at time zone 'UTC'), true, 1, '2019-12-15', '<p><br></p>', 'Optimizare proces vanzare', '0', NULL, 10, 1, NULL, 'prevention', 2) RETURNING id
ERROR: null value in column "reference" violates not-null constraint
DETAIL:  Failing row contains (19, null, Optimizare proces vanzare, null, 1, t, 0, 10, 2019-12-15, null, null, null, null, null, 2, <p><br></p>, prevention, 1, 2, 2019-12-08 12:02:50.767694, 2, 2019-12-08 12:02:50.767694).

2019-12-08 12:02:51,994 107395 DEBUG odoo odoo.service.model: IntegrityError
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 922, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 523, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 392, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 372, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-128>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 342, in _model_create_multi
    return create(self, [arg])
  File "/mnt/data/opt/odoo/addons/mgmtsystem_action/models/mgmtsystem_action.py", line 112, in create
    actions = super().create(vals_list)
  File "<decorator-gen-108>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 343, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 269, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-94>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 324, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 324, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/mnt/data/opt/odoo/addons/component_event/models/base.py", line 99, in create
    record = super(Base, self).create(vals)
  File "<decorator-gen-52>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 342, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 498, in create
    recs = super().create(vals_list)
  File "<decorator-gen-2>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 343, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3717, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3803, in _create
    cr.execute(query, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 163, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 240, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "reference" violates not-null constraint
DETAIL:  Failing row contains (19, null, Optimizare proces vanzare, null, 1, t, 0, 10, 2019-12-15, null, null, null, null, null, 2, <p><br></p>, prevention, 1, 2, 2019-12-08 12:02:50.767694, 2, 2019-12-08 12:02:50.767694).

2019-12-08 12:02:52,008 107395 WARNING odoo odoo.http: The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model: Action (mgmtsystem.action), Field: Reference (reference)

```

**Comment by pedrobaeza** [comment]
The field is marked as required:

https://github.com/OCA/management-system/blob/13.0/mgmtsystem_action/models/mgmtsystem_action.py#L39

so that's something normal and even more, it should appear as mandatory in the form as well.

Closing this as no valid issue.

**Comment by drajar** [comment]
The problem is not that the field is mamdatory, but the sequence mgmtsystem.action that is created in current company on install. If you try to create action in another company, will fail.

**Comment by pedrobaeza** [comment]
Yeah, that's something expected, as you have to either remove the company from the provided sequence or create a new sequence with the same code (duplicating the other) and changing company.
