### ISSUE TITLE
Odoo 14  -  Quality Management System 

### ISSUE THREAD

**Issue by D2O** [OCA/management-system#377]
odoo 14 comunity on debian 10

Error on install :-

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AssertionError: Element odoo has extra content: menuitem, line 7

**Comment by pedrobaeza** [comment]
Module is not migrated to that version.
