### ISSUE TITLE
mgmtsystem_nonconformity: causing JS traceback in Accounting App

### ISSUE THREAD

**Issue by yp-oerp** [OCA/management-system#587]
## Module
mgmtsystem_nonconformity

## Describe the bug
When attempting to validate bank statement lines or opening the 'discuss' feature in V16 Enterprise Accounting Reconciliation screen, an error traceback is displayed.

1. Install the mgmtsystem_nonconformity module.
2. Go to Accounting in v16 Enterprise -> Click on any journal which has items to reconcile
3. Click on discuss or try to validate a bank statement line

**Expected behavior**
No error!

**Additional context**
We are getting the below error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1472:101)
    at owl.App.handleError (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:2098:29)
    at Fiber._render (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1497:19)
    at Fiber.render (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1495:6)
    at ComponentNode.render (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1571:56)

Caused by: TypeError: Cannot read properties of undefined (reading 'data')
    at MessagingClass.template (eval at compile (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:2056:374), <anonymous>:66:50)
    at node.renderFn (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1613:210)
    at node.renderFn (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1614:207)
    at Fiber._render (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1496:96)
    at Fiber.render (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1495:6)
    at ComponentNode.render (http://localhost:8016/web/assets/9641-16f2c17/web.assets_common.min.js:1571:56)

This is caused by the javascript changes in the module, after commenting out the web.assets_backend in manifest of mgmtsystem_nonconformity module, the error is resolved.

**Comment by Sibert-Aerts** [comment]
We experienced this exact same error except when trying to edit a worksheet template (which opens a Studio editor view).

I fixed the error locally by prefixing `chatterTopbar.chatter.webRecord and` to the following `t-if` condition:
https://github.com/OCA/management-system/blob/d8f4653d6508a0e164b33c4250313cd2d55717db/mgmtsystem_nonconformity/static/src/components/chatter_topbar/chatter_topbar.xml#L19

If a maintainer could implement my fix into the OCA codebase, that would be nice.
