### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by max3903** [OCA/management-system#86]
# Impacted versions

7.0
# Steps to reproduce
- Create a nonconformity and fill in all the required form
- Click on "Send for analysis"
# Result

Error message:

```
Server Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/osv/osv.py", line 133, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/osv/osv.py", line 225, in exec_workflow
    res = self.exec_workflow_cr(cr, uid, obj, signal, *args)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/addons/audittrail/audittrail.py", line 538, in exec_workflow_cr
    return fct_src(cr, uid, model, method, *args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/osv/osv.py", line 218, in exec_workflow_cr
    return object._workflow_signal(cr, uid, [res_id], signal)[res_id]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/osv/orm.py", line 4034, in _workflow_signal
    result[res_id] = wf_service.trg_validate(uid, self._name, res_id, signal, cr)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/wkf_service.py", line 119, in trg_validate
    res2 = instance.validate(cr, id, ident, signal)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/instance.py", line 43, in validate
    workitem.process(cr, witem, ident, signal, force_running, stack=stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/workitem.py", line 60, in process
    ok = _split_test(cr, workitem, activity['split_mode'], ident, signal, stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/workitem.py", line 175, in _split_test
    _join_test(cr, t[0], t[1], ident, stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/workitem.py", line 183, in _join_test
    create(cr,[activity], inst_id, ident, stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/workitem.py", line 40, in create
    process(cr, res, ident, stack=stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/workitem.py", line 52, in process
    result = _execute(cr, workitem, activity, ident, stack)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/workitem.py", line 106, in _execute
    returned_action = wkf_expr.execute(cr, ident, workitem, activity)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/wkf_expr.py", line 67, in execute
    return _eval_expr(cr, ident, workitem, activity['action'])
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/workflow/wkf_expr.py", line 57, in _eval_expr
    ret = eval(line, env, nocopy=True)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/tools/safe_eval.py", line 288, in safe_eval
    return eval(test_expr(expr, _SAFE_OPCODES, mode=mode), globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/osv/orm.py", line 378, in function_proxy
    return attr(self._cr, self._uid, [self._id], *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/addons/mgmtsystem_nonconformity/model/mgmtsystem_nonconformity.py", line 222, in wkf_analysis
    cr, uid, ids, _('Analysis'), data=data, context=context
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112532-7-0-f156c2/openerp/addons/mgmtsystem_nonconformity/model/mgmtsystem_nonconformity.py", line 207, in case_send_note
    ''' % (o.state, data['state'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)
```
# Expected result

The nonconformity moves on to the next stage in the workflow.

**Comment by max3903** [comment]
Fixed in #87
